FROM quay.io/fedora/fedora-sericea:39

COPY usr /usr

RUN rpm-ostree override remove firefox firefox-langpacks && \
    rpm-ostree install podman-compose mbpfan && \
    systemctl enable rpm-ostreed-automatic.timer && \
    rpm-ostree cleanup -m && \
    ostree container commit
