FROM quay.io/fedora/fedora-silverblue:39

COPY usr /usr

RUN rpm-ostree override remove firefox firefox-langpacks gnome-software gnome-software-rpm-ostree && \
    rpm-ostree install podman-compose wl-clipboard mbpfan && \
    systemctl enable rpm-ostreed-automatic.timer && \
    rpm-ostree cleanup -m && \
    ostree container commit
